### ISSUE TITLE
Remove VOLUME declarations or allow non-root

### ISSUE THREAD

**Issue by v-byte-cpu** [caddyserver/caddy-docker#103]
I want to run server as non-root user. Unfortunately, running as non-root causes permission errors. So I extended your image to chown data and config folders:

```
FROM caddy:2-alpine
RUN chown -R nobody:nobody /data /config
USER nobody
ENTRYPOINT ["caddy", "run", "--config", "/Caddyfile", "--adapter", "caddyfile"]
```

**BUT**  [docker documentation](https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes) states that:

Changing the volume from within the Dockerfile: If any build steps change the data within the volume after it has been declared, those changes will be discarded.

**Comment by francislavoie** [comment]
Regarding running as non-root, we decided against it because it introduced issues with listening on low ports. https://github.com/caddyserver/caddy-docker/issues/24

I think if you're going to be running as non-root, you should override the `XDG_*` env vars instead of trying to reuse the `/data` and `/config` directories. Maybe something like this:

```
ENV XDG_CONFIG_HOME=/caddy/config
ENV XDG_DATA_HOME=/caddy/data
``` 

Then you won't problems conflicting with existing volumes and you can declare your own.

I'm not convinced that changing the default Dockerfile makes sense to accommodate this use-case because not having volumes is risky.

**Comment by v-byte-cpu** [comment]
Thank you for possible solution! I suppose in that case the issue can be closed. But nevertheless, it would be great if your image had a possible option to run as non-root.

**Comment by francislavoie** [comment]
Well, it is possible as you've shown yourself :stuck_out_tongue: 

I'll close it for now, thanks
