### ISSUE TITLE
Built react app not showing anything in local network (only works on localhost)

### ISSUE THREAD

**Issue by UserSina** [caddyserver/caddy-docker#173]
I have the following docker file for building a react app:

`Dockerfile.local`
``` Dockerfile
# First stage (build the base image)
FROM node:15.14.0-alpine3.10 AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

# Second stage (build the web server)
FROM caddy:2.3.0-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 3000
```

`Caddyfile.local`
```Caddyfile
http://localhost:3000 {
    root * /srv
    route {
        reverse_proxy /api* api-server:9000
        try_files {path} {path}/ /index.html
        file_server
    }
}
```

Here's my command when building the image:
```CMD
docker build \
  -t react-app-production:local \
  --build-arg CADDYFILE=Caddyfile.local \
  --build-arg BASE_URL=http://localhost:9000/api \
  -f Dockerfile.local .
```

When running **localhost:3000** on the computer the container is running on, I get my built react app just fine.

However when I try to open **http://192.168.1.5:3000** on another computer in the network (the IP of the machine the container is running on) I don't get any output. The page is blank and there is nothing in the console (no errors, no 404), only the favicon.ico is showing in the title bar.

Note that I have an express api running on **http://192.168.1.5:9000** and it returns a json response as intended when I open it.

**Comment by francislavoie** [comment]
That's because you have `localhost` as your host matcher. If Caddy doesn't see that as the hostname in the request, it responds to the request unhandled.

Instead, use `http://:3000` as your site address, or simply `:80` and do a port mapping like `-p 3000:80` when running the container.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
