### ISSUE TITLE
Manifest is missing

### ISSUE THREAD

**Issue by PortStone** [caddyserver/caddy-docker#19]
Is this in such an early development that we shouldn't use it anyways?

docker pull caddy/caddy
Using default tag: latest
Error response from daemon: manifest for caddy/caddy:latest not found: manifest unknown: manifest unknown

**Comment by mholt** [comment]
Ah, yes, we've been having this discussion...

I do not think it is in our or anyone's best interest to use a "latest" tag since people will undoubtedly use that in production and experience breaking changes. It's a user error, for sure, but if it's also the default, then it's unsafe for us to deploy to a "latest" tag, we risk breaking all those people's sites automatically.

**Comment by PortStone** [comment]
Ah okay I understand. Thank you very much this fixed it.
