### ISSUE TITLE
[Question] What's difference between 2 dockerhub repositories?

### ISSUE THREAD

**Issue by Sebor** [caddyserver/caddy-docker#194]
There are 2 repositories on dockerhub:
`https://hub.docker.com/_/caddy`
and
`https://hub.docker.com/r/caddy/caddy`
What is the difference between ones? I've noticed that the second one has more fresh versions of caddy (for example, I need a version 2.4.3)

**Comment by francislavoie** [comment]
The former is the official docker image, which we maintain but is deployed under the "official image" banner: https://docs.docker.com/docker-hub/official_images/. This involves the extra step of getting approval from Docker maintainers, e.g. https://github.com/docker-library/official-images/pull/10387. Right now, we happen to have an issue with this release, which @hairyhenderson hasn't had the time to resolve since Friday.

The latter is our CI build target. For example when we open PRs on this repo, they get built and pushed there for our testing before we send it off to the official image repo.

You should always use https://hub.docker.com/_/caddy, for stability.

If you need `v2.4.3` right away, then you can use the `builder` image variant for the time being, with a Dockerfile like this:

```Dockerfile
FROM caddy:2.4.2-builder AS builder

RUN xcaddy build v2.4.3

FROM caddy:2.4.2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

This will build a version of Caddy from source with version `v2.4.3` using `xcaddy`, our tool for making custom builds of Caddy.

**Comment by Sebor** [comment]
> Right now, we happen to have an issue with this release, which @hairyhenderson hasn't had the time to resolve since Friday.

Can I help somehow?

**Comment by hairyhenderson** [comment]
> Can I help somehow?

Thanks for the offer @Sebor!

The root issue is that I have a PR open to unblock this (https://github.com/caddyserver/caddy-docker/pull/193), however it failed in CI and I didn't have time to focus on it.

Looking at it briefly this morning, the issue seems pretty straightforward, so it should be solved soon.
