### ISSUE TITLE
Docker Hub - Caddy vulnerabilities are risky?

### ISSUE THREAD

**Issue by redr00t** [caddyserver/caddy-docker#289]
All Caddy images in docker have the following vulnerabilities:
Is it a false positive or should I really worry about it?
![image](https://user-images.githubusercontent.com/46618211/228487593-e75a5239-5173-406d-b783-8bcb2e7a27e5.png)

**Comment by hairyhenderson** [comment]
Hi @redr00t, thanks for reporting this.

for completeness, the screenshot comes from the tag view in DockerHub, like this one: https://hub.docker.com/layers/library/caddy/builder-alpine/images/sha256-4fa7d446d8f18e37cec1fe9b3b9a1e0e93807a3b06dc57ec020888c11d21cf93?context=explore

I'll look into this.

**Comment by snieguu** [comment]
@hairyhenderson Do You have any more insights or info?

**Comment by hairyhenderson** [comment]
These are coming from the `xcaddy` binary, which was built with an older Go binary. It should be re-built with 1.20.3. Same goes for the `caddy` binary.

@mholt do you know when the next release of `xcaddy` is happening?

**Comment by dbrennand** [comment]
Hi all,

Should this have been resolved by `v0.3.3` of `xcaddy`?

The version of `stdlib` is now `1.20` (different from the original screenshot from @redr00t) but Docker Hub is still reporting CVEs, one with a score of 9.8 in stdlib 😞 

![image](https://github.com/caddyserver/caddy-docker/assets/52419383/e692dd0a-cfee-4bc4-a9af-ebc07061eaa1)

**Comment by hairyhenderson** [comment]
@dbrennand You're looking at a different tag from the original (`latest`, vs `builder-alpine`).  

As I mentioned in [an earlier comment](https://github.com/caddyserver/caddy-docker/issues/289#issuecomment-1521814727), both `xcaddy` and `caddy` needed to be re-built with Go 1.20.3+. There's a new Caddy beta available (`2.7.0-beta.1`) that you can try out - it scans clean:

https://hub.docker.com/layers/library/caddy/2.7/images/sha256-7951c4c3a58a42562e4cd3ecfb3eb2cef6e072a640d80256c03b009678a8df90?context=explore

Given that this issue was for the builder image originally, I'm going to close it.
