### ISSUE TITLE
Project name continuity

### ISSUE THREAD

**Issue by pascalandy** [caddyserver/caddy-docker#41]
I find it confusing that the dockerhub caddy name project is not consistent with the github project.
 caddyserver VS caddy.

- https://github.com/caddyserver/caddy-docker for issues with this image, or - 
- https://github.com/caddyserver/caddy for issues with Caddy itself.
- https://hub.docker.com/r/caddy/caddy/tags

Do you plan to stream line this? Or maybe had a note in the README about this fact.

Cheers!

**Comment by francislavoie** [comment]
For GitHub, problem is that the "caddy" org name was taken, so "caddyserver" was used as a fallback.

Having the Docker scripts in the caddy repo is possible, but splitting the distribution stuff from the actual project was preferred. We also have "caddyserver/dist" for package distros.

For Docker Hub, we managed to get the "caddy" org which is the ideal. Right now it's "caddy/caddy", because that's how it needs to read for non-official images. The plan is to try and get it accepted as an official images soon.

So with all that said, I'd say that no, no changes are planned to consolidate those aside from the DockerHub image potentially becoming just "caddy".

**Comment by mholt** [comment]
We had to work really hard to get the name `caddy` at Docker, too. I've tried repeatedly to get the `caddy` GitHub space and Twitter handle, but to no avail. Trademark is useless here since they aren't representing a brand, either.
