### ISSUE TITLE
Let's have official images using UBI

### ISSUE THREAD

**Issue by Ilyes512** [caddyserver/caddy-docker#5]
Original ticket by @Conan-Kudo:

> There's a great, high-quality set of base images with good commercial support that we should leverage for the official Caddy container images: The Red Hat Universal Base Image. Using ubi8 as the base gives us an excellent, well-supported stack that will work well for community and commercial users alike.
> 
> @fatherlinux has been working on this for a while now, and I think he'd be pleased as punch if we used it for caddy. And if there's anything missing we need, we can ask him about fixing it. It would also let us leverage the official Caddy RPMs that @carlwgeorge has made...

**Comment by hairyhenderson** [comment]
IMO this isn't a good idea for the official Docker images, since those should ideally be super-minimalistic `FROM scratch` or Alpine-based images.

I'd contend that this would have the detrimental effect of increasing potential attack surface area, due to having libraries and packages that are totally unnecessary to running Caddy.

**Comment by carlwgeorge** [comment]
Alpine still has libraries that Caddy doesn't use.  And while there are fewer of them, they undergo significantly less testing than the libraries in a distribution like RHEL or Debian.  There is a reason that most (all?) of Docker's official images latest tag still use Debian and not Alpine.  This article goes into more depth on this topic.

https://crunchtools.com/comparison-linux-container-images/

**Comment by hairyhenderson** [comment]
> Alpine still has libraries that Caddy doesn't use.

Yup, totally correct. I mainly build images based on Alpine when they're intended for development or debugging, so I can exec into a shell.

When building a production image wrapping a Go binary (such as Caddy), I always recommend using `FROM scratch`, and I see that @fatherlinux does too (in the comments to that specific article).

There was an announcement a few years ago (see https://brianchristner.io/docker-is-moving-to-alpine-linux/) where all official images were moving to Alpine by default, though it seems that didn't get entirely finished.

There's no reason we can't ship a mix of Caddy images based on different distros. I'd suggest however focusing on `scratch` and `alpine` as a start.

**Comment by Conan-Kudo** [comment]
> When building a production image wrapping a Go binary (such as Caddy), I always recommend using FROM scratch, and I see that @fatherlinux does too (in the comments to that specific article).

I typically don't recommend `FROM scratch` images because "single binary Go software" is a lie. Aside from the fact that you need a libc somewhere (whether it's statically linked or dynamically linked, it's still there), you also wind up needing several important pieces of critical data files and configuration infrastructure. You'll also definitely wind up needing certain core binaries, or at least the ability to grab them easily enough when debugging/configuring on the fly from the container.

In my view, `FROM scratch` containers generally provide a disservice to developers and users, because it misleads on vulnerability semantics (exposure, content usage, etc.) and reduces the ability for performing useful diagnostics or extensions of the container for specific use-cases (for example, maybe more plugins are needed?).
