### ISSUE TITLE
adding 'tzdata' package for timezone variables to work.

### ISSUE THREAD

**Issue by DoTheEvo** [caddyserver/caddy-docker#58]
The date is UTC otherwise, dont think it affects other stuff than logs, but from my limited exposure to docker its pretty widespread to have TZ env variable set to local time.

On my arch host, mounting `/etc/localtime` never worked, so env variables is the only way.

![img](https://i.imgur.com/XP8xBSK.png)

**Comment by hairyhenderson** [comment]
@DoTheEvo in my experience it's not _that_ common to have `tzdata` installed in containers like this. Personally I'm not convinced that it adds much value. In production, I always use UTC regardless of where containers are running - reduces confusion.

Also `tzdata` is a fairly large package, and one of the goals of this image is to remain as lightweight as possible while still providing value.

If you want to build your own image from this with `tzdata` for your uses, that's a pretty simple `Dockerfile`:

```docker
FROM caddy/caddy:alpine

RUN apk add --no-cache tzdata
```

**Comment by DoTheEvo** [comment]
Well, I personally think that having confidence in having correct time inside container outweighs few kB download and few MBs install size.. but thats for me and my use case.

**Comment by hairyhenderson** [comment]
@DoTheEvo it could be argued that UTC is the _only_ way to have "correct" time consistently 😉. Local time zones are confusion waiting to happen when it comes to log entries. Just a couple weeks ago, I and a colleague wasted a couple hours of work because we were correlating time series that were offset from each other and we didn't realize it.

**Comment by dadatuputi** [comment]
I would tend to agree on using UTC for logging, however I'm using Caddy with a couple other containers, some of which use crons, where it makes sense to use local time for things like "at 3am do this thing". For my use case, I run the risk of logs being not in the same time zone. The user always has the choice to NOT pass TZ variables, and having the option is good.

**Comment by francislavoie** [comment]
You also have the option of making your own Dockerfile with one added line to install `tzdata`. There's no reason it needs to be in the image by default. It adds bloat for no reason for many people who will never need it.

**Comment by hairyhenderson** [comment]
Maybe worth mentioning here - Go 1.15 (beta right now) has a new [`time/tzdata`](https://tip.golang.org/pkg/time/tzdata/) package in the standard library that, if caddy were compiled with it, would add this functionality without needing a `tzdata` distro package.

That being said, I don't think we'll see a version of Caddy that requires 1.15 for a while (due to distro compatibility constraints), and it does bloat the binary.

**Comment by francislavoie** [comment]
@mholt we could consider building with `go build -tags timetzdata` when Go 1.15 is released. See https://tip.golang.org/doc/go1.15#time/tzdata

That would mean we don't need to require Go 1.15 (and continue to have a 1.14 minimum) but we can make our official builds with that flag to have it included, along with the other 1.15 compiler improvements.

**Comment by mholt** [comment]
I was thinking about it, but I'm currently on a quest to decrease the binary (and go.sum) size (there should be some significant improvements in the coming months).
