### ISSUE TITLE
Qualify Caddy Docker Hub image as Docker Certified

### ISSUE THREAD

**Issue by GalacticLion7** [caddyserver/caddy-docker#78]
The Caddy Docker Hub image should apply for Docker Certified qualification, just like most other popular Docker Hub images. This will not change Caddy itself.

According to the official Docker documentation:

> The Docker Certification program for Containers and Plugins is designed for both technology partners and enterprise customers to recognize high-quality Containers and Plugins, provide collaborative support, and ensure compatibility with the Docker Enterprise platform. Docker Certified products give enterprises a trusted way to run more technology in containers with support from both Docker and the publisher. The Docker Technology Partner guide explains the Technology Partner program, inclusive of process and requirements to Certify Containers and Plugins.

More information:

https://docs.docker.com/docker-hub/publish/publisher_faq/#what-is-the-certification-program-for-containers-and-plugins-and-what-are-some-benefits
https://docs.docker.com/docker-hub/publish/certify-images/

**Comment by mholt** [comment]
We looked into this, but my understanding is that there is some non-trivial costs involved.

**Comment by hairyhenderson** [comment]
> just like most other popular Docker Hub images

Eh? Which popular images are "Docker Certified?" If you look at the list of [certified images](https://hub.docker.com/search?q=&type=image&image_filter=&certification_status=certified) and compare with the list of [official images](https://hub.docker.com/search?q=&type=image&image_filter=official), it's pretty obvious that this isn't really the right list for open-source software like Caddy.

Anyway, we definitely _don't_ want this. "Docker Certified" images are certified for compatibility with Docker Enterprise Edition, which frankly is really only interesting to enterprise (i.e. commercial) software.

Also, since we looked into this, Mirantis bought the Docker Enterprise business, and so the certification would come from Mirantis now, not Docker.

There's really no benefit to being "Docker Certified" (really "Mirantis Certified" now), at this point. None of Caddy's competitors are part of this program anyway.

**Comment by GalacticLion7** [comment]
Lol, I was actually confused between "Docker Certified" images and ["Docker Official" images](https://docs.docker.com/docker-hub/official_images/). I was just interested in the image being in being official, not certified. It seemed to have been recently, and I didn't notice it. Anyways, thanks!

**Comment by hairyhenderson** [comment]
@GalacticLion7 Thanks for following up! The terminology is confusing 😉
