### ISSUE TITLE
No access or error logs

### ISSUE THREAD

**Issue by msandres13** [caddyserver/caddy-docker#92]
Hi, I am struggling with getting error and access logs for caddy.
What I would like to have is just all access logs to /var/log/caddy/access.log and same for error.log
Can you please provide some help in your example?
An example for with common options for a standard server would be great.
I was also searching for a while how to use my email to get an account at letsencrypt so I get the expire emails.
It is very nice that you have all these minimal examples which show how easy it is. Anyways once you try to use it the struggling starts.

Thanks for your help and maybe an update on the dockerhub "readme" to show real world examples.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy! Sorry we good long to get to you, I missed the notification for this issue somehow.

We typically ask that you ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests relating directly to the docker image rather than usage. Don't forget to fill out the thread template so we can help you!

That said, here's a couple links that should help you find what you need:

- The `log` directive is what you want to use to enable access logs and have them written somewhere specific: https://caddyserver.com/docs/caddyfile/directives/log
- In Caddy v2, there's no concept of a separate error log location. You can read this for an explanation of how logging works in Caddy v2: https://caddyserver.com/docs/logging
